avator_6:
 preparation: True
 bbox_shift: 5
 video_path: "data/example/huangjinbiao6/huang720p.25fps.170s.mov"
 lower_green: [40, 60, 130]
 upper_green: [77, 255, 255]
 audio_clips:
     audio_0: "data/example/huangjinbiao/huang.short.wav"
     audio_1: "data/audio/sun.wav"