avator_5:
 preparation: True
 bbox_shift: 5
 video_path: "data/example/huangjinbiao/huang720p.30fps.mov"
 audio_clips:
     audio_0: "data/example/huangjinbiao/huang.short.wav"
     audio_1: "data/audio/sun.wav"
 
  

