avator_3:
 preparation: True
 bbox_shift: 5
 video_path: "data/example/liyubin60s.720p.mp4"
 audio_clips:
     audio_0: "data/audio/yongen.wav"
     audio_1: "data/audio/sun.wav"
     audio_2: "data/audio/sun.wav"
 
  

